spring.datasource.url=jdbc:h2:mem:streamingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# JWT
jwt.secret=streaming-secret-key-ebac-2024-muito-segura
jwt.expiration=3600000
